// Brighter Land International School (BLIS) & Brighter Land Global Mission
// Gallery & Impact Data Records

export const galleryCategories = [
  { id: "all", name: "All Gallery", icon: "fas fa-th-large", count: 38 },
  { id: "zoo", name: "Jos Zoo Excursion", icon: "fas fa-paw", count: 8 },
  { id: "airport", name: "Jos Airport Visit", icon: "fas fa-plane-departure", count: 7 },
  { id: "museum", name: "Jos Museum Tour", icon: "fas fa-landmark", count: 3 },
  { id: "supporter", name: "USA Supporter Visit", icon: "fas fa-globe-americas", count: 5 },
  { id: "scholarship", name: "Scholarship Grants", icon: "fas fa-graduation-cap", count: 7 },
  { id: "borehole", name: "Clean Water Boreholes", icon: "fas fa-tint", count: 6 },
  { id: "donations", name: "School Relief Donations", icon: "fas fa-hands-helping", count: 5 },
  { id: "training", name: "Teacher Training & Life", icon: "fas fa-chalkboard-teacher", count: 3 },
]

export const galleryItems = [
  // -------------------------------------------------------------
  // 1. JOS ZOO & WILDLIFE PARK EXCURSION
  // -------------------------------------------------------------
  {
    id: "zoo-1",
    type: "image",
    category: "zoo",
    group: "excursions",
    title: "Jos Wildlife Park & Zoo Excursion",
    categoryLabel: "Jos Zoo Visit",
    image: "/images/gallery/zoo1.jpeg",
    location: "Jos Wildlife Park, Plateau State",
    date: "Academic Field Excursion",
    description: "BLIS scholars embarking on an experiential field expedition to explore biodiversity, animal science, and natural conservation at the Jos Wildlife Park.",
    featured: true,
  },
  {
    id: "zoo-2",
    type: "image",
    category: "zoo",
    group: "excursions",
    title: "Guided Nature & Wildlife Observation",
    categoryLabel: "Jos Zoo Visit",
    image: "/images/gallery/zoo2.jpeg",
    location: "Jos Zoo, Plateau State",
    date: "Academic Field Excursion",
    description: "Students observing diverse wildlife exhibits, learning about biological taxonomy and the preservation of indigenous Nigerian ecosystems.",
    featured: false,
  },
  {
    id: "zoo-3",
    type: "image",
    category: "museum",
    group: "excursions",
    title: "Earliest Cars in Nigeria Exhibition",
    categoryLabel: "Jos Museum Tour",
    image: "/images/gallery/zoo3.jpeg",
    location: "National Museum Jos / Vintage Vehicles",
    date: "Cultural Heritage Tour",
    description: "BLIS scholars viewing the historic exhibition of some of the earliest motorcars and vintage automobiles in Nigeria preserved at the Jos Museum.",
    featured: true,
  },
  {
    id: "zoo-4",
    type: "image",
    category: "museum",
    group: "excursions",
    title: "Early Train & Steam Locomotive Exhibition",
    categoryLabel: "Jos Museum Tour",
    image: "/images/gallery/zoo4.jpeg",
    location: "National Museum Jos / Railway Heritage",
    date: "Cultural Heritage Tour",
    description: "Students exploring one of Nigeria's earliest steam train locomotives and historic railway coaches preserved at the Jos National Museum grounds.",
    featured: false,
  },
  {
    id: "zoo-5",
    type: "image",
    category: "zoo",
    group: "excursions",
    title: "Learning Beyond the Four Classroom Walls",
    categoryLabel: "Jos Zoo Visit",
    image: "/images/gallery/zoo5.jpeg",
    location: "Jos Wildlife Park",
    date: "Academic Field Excursion",
    description: "Experiential learning fosters deeper curiosity and broadens intellectual horizons for young minds.",
    featured: false,
  },
  {
    id: "zoo-6",
    type: "image",
    category: "zoo",
    group: "excursions",
    title: "Fauna & Flora Botanical Trail Walk",
    categoryLabel: "Jos Zoo Visit",
    image: "/images/gallery/zoo6.jpeg",
    location: "Jos Wildlife Sanctuary",
    date: "Academic Field Excursion",
    description: "Walking the scenic conservation trails while taking scientific notes and discussing environmental stewardship.",
    featured: false,
  },
  {
    id: "zoo-7",
    type: "image",
    category: "zoo",
    group: "excursions",
    title: "Friendship & Discovery in the Outdoors",
    categoryLabel: "Jos Zoo Visit",
    image: "/images/gallery/zoo7.jpeg",
    location: "Jos Wildlife Park",
    date: "Academic Field Excursion",
    description: "Creating unforgettable childhood memories, teamwork, and peer bonding during school educational tours.",
    featured: false,
  },
  {
    id: "museum-video",
    type: "video",
    category: "museum",
    group: "excursions",
    title: "Jos Museum Live Video Highlights",
    categoryLabel: "Jos Museum Video",
    src: "/images/gallery/zoovideo.mp4",
    poster: "/images/gallery/zoo3.jpeg",
    location: "National Museum Jos, Plateau State",
    date: "Video Chronicle",
    description: "Live video clips capturing scholars discovering historical artifacts, ancient vehicles, and cultural heritage at the Jos Museum.",
    featured: true,
  },

  // -------------------------------------------------------------
  // 2. YAKUBU GOWON AIRPORT, JOS EXCURSION
  // -------------------------------------------------------------
  {
    id: "airport-1",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Arrival at Yakubu Gowon Airport, Jos",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport1.jpeg",
    location: "Yakubu Gowon Airport (Heipang, Jos)",
    date: "Aviation & Science Tour",
    description: "BLIS students arriving at the airport for a comprehensive guided tour of civil aviation operations, air navigation, and flight engineering.",
    featured: true,
  },
  {
    id: "airport-2",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Scholars Beside the Runway",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport2.jpeg",
    location: "Yakubu Gowon Airport Runway, Jos",
    date: "Aviation & Science Tour",
    description: "BLIS scholars standing beside the airport runway apron, observing aircraft landing zones, runway markers, and flight logistics.",
    featured: false,
  },
  {
    id: "airport-3",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Tarmac & Runway Facilities Tour",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport3.jpeg",
    location: "Jos Airport Airfield",
    date: "Aviation & Science Tour",
    description: "Scholars observing the aircraft apron, runway lighting, and ground service equipment up close.",
    featured: true,
  },
  {
    id: "airport-4",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Aviation Safety & Flight Mechanics Session",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport4.jpeg",
    location: "Jos Airport Inspection Wing",
    date: "Aviation & Science Tour",
    description: "Airport personnel teaching scholars about the aerodynamics of flight, safety gear, and emergency management.",
    featured: false,
  },
  {
    id: "airport-5",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Inspiring Future Aerospace Leaders",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport5.jpeg",
    location: "Jos Airport Facility",
    date: "Aviation & Science Tour",
    description: "Planting the seeds for future commercial pilots, aeronautical engineers, and air traffic directors among our scholars.",
    featured: false,
  },
  {
    id: "airport-6",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Faculty & Scholars on the Airfield",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport6.jpeg",
    location: "Yakubu Gowon Airport",
    date: "Aviation & Science Tour",
    description: "Group photo commemorating a transformative practical exposure to Plateau State's primary aviation corridor.",
    featured: false,
  },
  {
    id: "airport-7",
    type: "image",
    category: "airport",
    group: "excursions",
    title: "Global Logistics & Transportation Learning",
    categoryLabel: "Jos Airport Visit",
    image: "/images/gallery/airport7.jpeg",
    location: "Jos Airport Departures",
    date: "Aviation & Science Tour",
    description: "Practical connection between classroom social studies and real-world international connectivity and commerce.",
    featured: false,
  },

  // -------------------------------------------------------------
  // 3. JOS NATIONAL MUSEUM & HERITAGE TOUR
  // -------------------------------------------------------------
  {
    id: "museum-1",
    type: "image",
    category: "museum",
    group: "excursions",
    title: "National Museum Jos Heritage Expedition",
    categoryLabel: "Jos Museum Tour",
    image: "/images/gallery/museum.jpeg",
    location: "National Museum Jos, Plateau State",
    date: "Cultural Heritage Tour",
    description: "BLIS scholars discovering the rich historical heritage of Nigeria at the renowned Jos National Museum, established in 1952.",
    featured: true,
  },
  {
    id: "museum-2",
    type: "image",
    category: "museum",
    group: "excursions",
    title: "Ancient Nok Terracotta & Archaeology",
    categoryLabel: "Jos Museum Tour",
    image: "/images/gallery/museum1.jpeg",
    location: "National Museum Galleries",
    date: "Cultural Heritage Tour",
    description: "Students studying 2,500-year-old Nok terracotta sculptures, ancient metalwork, and traditional craft traditions.",
    featured: false,
  },
  {
    id: "museum-3",
    type: "image",
    category: "museum",
    group: "excursions",
    title: "Preserving Nigerian History & Heritage",
    categoryLabel: "Jos Museum Tour",
    image: "/images/gallery/museum2.jpeg",
    location: "Jos Museum Complex",
    date: "Cultural Heritage Tour",
    description: "Instilling deep cultural pride and historical consciousness to nurture grounded, culturally aware global citizens.",
    featured: true,
  },

  // -------------------------------------------------------------
  // 4. USA SUPPORTER & INTERNATIONAL PARTNER VISIT
  // -------------------------------------------------------------
  {
    id: "supporter-1",
    type: "image",
    category: "supporter",
    group: "partnerships",
    title: "Welcoming Our Beloved USA Mission Partner",
    categoryLabel: "USA Supporter Visit",
    image: "/images/gallery/supporter.jpeg",
    location: "Brighter Land International School Campus",
    date: "International Delegation",
    description: "A joyous welcome as our esteemed supporter and partner from the United States visits BLIS to witness firsthand the lives being transformed.",
    featured: true,
  },
  {
    id: "supporter-2",
    type: "image",
    category: "supporter",
    group: "partnerships",
    title: "Picture with Our USA Supporter",
    categoryLabel: "USA Supporter Visit",
    image: "/images/gallery/supporter2.jpeg",
    location: "Brighter Land International School Campus",
    date: "International Delegation",
    description: "Scholars, staff, and leadership posing for a memorable picture with our beloved mission partner and supporter from the USA.",
    featured: false,
  },
  {
    id: "supporter-3",
    type: "image",
    category: "supporter",
    group: "partnerships",
    title: "Campus Development & Infrastructure Inspection",
    categoryLabel: "USA Supporter Visit",
    image: "/images/gallery/supporter3.jpeg",
    location: "BLIS Campus Grounds",
    date: "International Delegation",
    description: "School management presenting ongoing classroom developments, computer laboratory upgrades, and expansion milestones.",
    featured: true,
  },
  {
    id: "supporter-4",
    type: "image",
    category: "supporter",
    group: "partnerships",
    title: "Strategic Educational & Mission Collaboration",
    categoryLabel: "USA Supporter Visit",
    image: "/images/gallery/supporter4.jpeg",
    location: "School Administrative Wing",
    date: "International Delegation",
    description: "Deliberating on sustainable scholarship programs and mission expansion alongside Rev. Fidelis Gambo and school deans.",
    featured: false,
  },
  {
    id: "supporter-5",
    type: "image",
    category: "supporter",
    group: "partnerships",
    title: "United in Faith, Service & Compassion",
    categoryLabel: "USA Supporter Visit",
    image: "/images/gallery/supporter5.jpeg",
    location: "BLIS Assembly Hall",
    date: "International Delegation",
    description: "Closing fellowship and thanksgiving prayers with teachers, scholars, and our international partners in mission.",
    featured: false,
  },

  // -------------------------------------------------------------
  // 5. SCHOLARSHIP GIVERS & BENEFICIARIES
  // -------------------------------------------------------------
  {
    id: "scholarship-1",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Scholarship Presentation & Awarding Ceremony",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship1.jpeg",
    location: "BLIS Auditorium, Jos",
    date: "Scholarship Endowment",
    description: "Awarding comprehensive tuition and resource scholarships to high-performing orphans and less-privileged children.",
    featured: true,
  },
  {
    id: "scholarship-2",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Scholarship Beneficiary Students",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship2.jpeg",
    location: "BLIS Campus, Jos",
    date: "Scholarship Endowment",
    description: "Bright scholars and scholarship beneficiaries of Brighter Land International School whose tuition and educational needs are supported.",
    featured: false,
  },
  {
    id: "scholarship-3",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Sponsors Meeting Beneficiary Families",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship3.jpeg",
    location: "BLIS School Hall",
    date: "Scholarship Endowment",
    description: "Generous donors and sponsors meeting directly with beneficiary scholars and their families in an atmosphere of fellowship.",
    featured: false,
  },
  {
    id: "scholarship-4",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Parents of the Beneficiaries",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship4.jpeg",
    location: "BLIS Assembly Grounds",
    date: "Scholarship Endowment",
    description: "Parents and guardians of scholarship beneficiaries gathered to celebrate academic grants and express appreciation.",
    featured: true,
  },
  {
    id: "scholarship-5",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Celebrating Academic Growth & Character",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship5.jpeg",
    location: "BLIS Assembly Grounds",
    date: "Scholarship Endowment",
    description: "Recognizing scholar beneficiaries who have maintained straight-A performance and exemplary Christian character.",
    featured: false,
  },
  {
    id: "scholarship-6",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Presenting Scholarship Award",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship6.jpeg",
    location: "BLIS Auditorium",
    date: "Scholarship Endowment",
    description: "Official presentation of academic scholarship certificates and educational award grants to outstanding students.",
    featured: false,
  },
  {
    id: "scholarship-7",
    type: "image",
    category: "scholarship",
    group: "impact",
    title: "Nurturing Future Nation Builders",
    categoryLabel: "Scholarship Grants",
    image: "/images/gallery/scholarship7.jpeg",
    location: "BLIS Campus",
    date: "Scholarship Endowment",
    description: "Every scholarship awarded is an investment into a future doctor, engineer, missionary, teacher, and ethical leader.",
    featured: false,
  },

  // -------------------------------------------------------------
  // 6. CLEAN WATER BOREHOLE DONATIONS (BRIGHTER LAND GLOBAL MISSION)
  // -------------------------------------------------------------
  {
    id: "borehole-1",
    type: "image",
    category: "borehole",
    group: "mission",
    title: "Clean Water Borehole Commissioning",
    categoryLabel: "Clean Water Boreholes",
    image: "/images/gallery/borehole1.jpeg",
    location: "Plateau State Host Community",
    date: "BLGM Community Outreach",
    description: "Brighter Land Global Mission commissioning a dedicated solar-powered borehole to provide free, safe drinking water to an entire community.",
    featured: true,
  },
  {
    id: "borehole-2",
    type: "image",
    category: "borehole",
    group: "mission",
    title: "Joyous Community Water Dedication",
    categoryLabel: "Clean Water Boreholes",
    image: "/images/gallery/borehole2.jpeg",
    location: "Community Water Point",
    date: "BLGM Community Outreach",
    description: "Community elders, women, and children celebrating the arrival of clean running water right in their village.",
    featured: false,
  },
  {
    id: "borehole-3",
    type: "image",
    category: "borehole",
    group: "mission",
    title: "Eradicating Waterborne Disease & Hardship",
    categoryLabel: "Clean Water Boreholes",
    image: "/images/gallery/borehole3.jpeg",
    location: "Rural Water Station",
    date: "BLGM Community Outreach",
    description: "Eliminating the dangerous miles-long daily trek for stream water, protecting children and mothers from waterborne infections.",
    featured: true,
  },
  {
    id: "borehole-4",
    type: "image",
    category: "borehole",
    group: "mission",
    title: "Dedicating the Water Well to God & Humanity",
    categoryLabel: "Clean Water Boreholes",
    image: "/images/gallery/borehole4.jpeg",
    location: "Outreach Location, Plateau State",
    date: "BLGM Community Outreach",
    description: "Rev. Fidelis Gambo and mission associates offering dedication prayers as clean, refreshing water flows abundantly.",
    featured: false,
  },
  {
    id: "borehole-5",
    type: "image",
    category: "borehole",
    group: "mission",
    title: "Sustainable Clean Water Infrastructure",
    categoryLabel: "Clean Water Boreholes",
    image: "/images/gallery/borehole5.jpeg",
    location: "Community Center",
    date: "BLGM Community Outreach",
    description: "Engineered with durable overhead storage and automated pumping to guarantee 24/7 reliable water access for hundreds of residents.",
    featured: false,
  },
  {
    id: "borehole-6",
    type: "image",
    category: "borehole",
    group: "mission",
    title: "The Gospel in Action Through Living Water",
    categoryLabel: "Clean Water Boreholes",
    image: "/images/gallery/borehole6.jpeg",
    location: "Village Water Hub",
    date: "BLGM Community Outreach",
    description: "Meeting physical thirst with pure water and spiritual thirst with the Gospel of Jesus Christ across underserved territories.",
    featured: false,
  },

  // -------------------------------------------------------------
  // 7. SCHOOL & EDUCATIONAL RELIEF DONATIONS (BLGM)
  // -------------------------------------------------------------
  {
    id: "school-1",
    type: "image",
    category: "donations",
    group: "mission",
    title: "Educational Relief & School Supply Donations",
    categoryLabel: "School Relief Donations",
    image: "/images/gallery/school1.jpeg",
    location: "Underserved Community School, Plateau State",
    date: "BLGM Education Relief",
    description: "Brighter Land Global Mission donating essential classroom supplies, writing materials, and instructional tools to struggling rural schools.",
    featured: true,
  },
  {
    id: "school-2",
    type: "image",
    category: "donations",
    group: "mission",
    title: "Mobile School Donation Outreach",
    categoryLabel: "School Relief Donations",
    image: "/images/gallery/school2.jpeg",
    location: "Community Outreach by BLGM",
    date: "BLGM Education Relief",
    description: "Brighter Land Global Mission mobile school donation outreach distributing learning supplies, school uniforms, and educational aids directly to rural community pupils.",
    featured: false,
  },
  {
    id: "school-3",
    type: "image",
    category: "donations",
    group: "mission",
    title: "Equipping Rural Teachers & Classrooms",
    categoryLabel: "School Relief Donations",
    image: "/images/gallery/school3.jpeg",
    location: "Community Learning Center",
    date: "BLGM Education Relief",
    description: "Furnishing classrooms with whiteboards, textbooks, and teacher resource guides to elevate the standard of learning.",
    featured: true,
  },
  {
    id: "school-4",
    type: "image",
    category: "donations",
    group: "mission",
    title: "Radiant Smiles of Hope on Children's Faces",
    categoryLabel: "School Relief Donations",
    image: "/images/gallery/school4.jpeg",
    location: "Community School Grounds",
    date: "BLGM Education Relief",
    description: "The joy of children knowing that God loves them and that brothers and sisters in Christ care for their future.",
    featured: false,
  },
  {
    id: "school-5",
    type: "image",
    category: "donations",
    group: "mission",
    title: "Transforming Communities Through Education",
    categoryLabel: "School Relief Donations",
    image: "/images/gallery/school5.jpeg",
    location: "Mission Outreach Venue",
    date: "BLGM Education Relief",
    description: "Building sustainable pathways out of poverty and illiteracy through ongoing community school support and mentorship.",
    featured: false,
  },

  // -------------------------------------------------------------
  // 8. TEACHER TRAINING & CAMPUS LIFE
  // -------------------------------------------------------------
  {
    id: "train-1",
    type: "image",
    category: "training",
    group: "campus",
    title: "Faculty Professional Pedagogy Workshop",
    categoryLabel: "Teacher Training",
    image: "/images/gallery/teachers-training.jpeg",
    location: "BLIS Resource Center",
    date: "Faculty Development",
    description: "Regular intensive workshops equipping our teachers with modern pedagogical strategies, digital competencies, and child-centered methodologies.",
    featured: true,
  },
  {
    id: "train-2",
    type: "image",
    category: "training",
    group: "campus",
    title: "Pastoral Care & Classroom Excellence Training",
    categoryLabel: "Teacher Training",
    image: "/images/gallery/teachers-training2.jpeg",
    location: "BLIS Staff Suite",
    date: "Faculty Development",
    description: "Training educators to blend academic rigor with compassionate Christian mentorship for every scholar.",
    featured: false,
  },
  {
    id: "train-3",
    type: "image",
    category: "training",
    group: "campus",
    title: "Extracurricular Sports, Games & Teamwork",
    categoryLabel: "Campus Life & Sports",
    image: "/images/gallery/games1.jpeg",
    location: "BLIS Sports Grounds",
    date: "Student Life",
    description: "Fostering physical wellness, sportsmanship, and leadership through lively athletic games and team competitions.",
    featured: true,
  },
]

// Impact Highlights for Counter & Showcase
export const impactStats = [
  { id: 1, number: "3+", label: "Major Educational Excursions", sub: "Zoo, Airport & National Museum", icon: "fas fa-bus" },
  { id: 2, number: "50+", label: "Scholarships & Grants Awarded", sub: "For orphans, missionary & less-privileged children", icon: "fas fa-graduation-cap" },
  { id: 3, number: "100%", label: "Clean Water Community Boreholes", sub: "Donated to rural Plateau communities by BLGM", icon: "fas fa-tint" },
  { id: 4, number: "1,000+", label: "Pupils & Families Impacted", sub: "Through school donations & mother ministry outreach", icon: "fas fa-hands-helping" },
]

// Documentary & Interview Videos
export const missionVideos = {
  founderInterview: {
    title: "The Genesis & Mandate of Brighter Land",
    subtitle: "Interview with Rev. Fidelis Gambo • Founder & Proprietor",
    src: "/images/gallery/mission.mp4",
    poster: "/images/proprietor.png",
    duration: "Full Documentary",
    description: "Rev. Fidelis Gambo shares the divine vision behind Brighter Land Global Mission, how compassion for vulnerable children inspired the founding of Brighter Land International School, and the continuing mandate to transform lives across Plateau State and Nigeria.",
    takeaways: [
      {
        title: "The Divine Mandate",
        desc: "How the Brighter Land Global Mission was birthed to take the Gospel and practical social compassion into underserved communities.",
      },
      {
        title: "Birthing the School (BLIS)",
        desc: "Establishing a premier center of academic excellence and Christian virtues in Jos to nurture children from Crèche to Secondary.",
      },
      {
        title: "Reaching the Vulnerable",
        desc: "A steadfast commitment to scholarships for orphans, missionary children, and conflict-affected families.",
      },
      {
        title: "Community Boreholes & Relief",
        desc: "Extending Christ's love through clean water boreholes, school supply donations, and teacher empowerment.",
      },
    ],
  },
  museumTour: {
    title: "Scholars Tour: Jos National Museum & Heritage",
    src: "/images/gallery/zoovideo.mp4",
    poster: "/images/gallery/zoo3.jpeg",
    description: "Live clips of BLIS scholars exploring historical artifacts, ancient steam locomotives, and Nigeria's earliest cars at the Jos Museum.",
  },
}
